### ISSUE TITLE
Filtering DATASource

### ISSUE THREAD

**Issue by dneykov** [SyncDB/DATASource#105]
Is it possible to filter DataSource using UISearchBar?
I'm trying but without success. Any help will be appreciated.
Thanks.

**Comment by 3lvis** [comment]
Hi @dneykov,

If you change the `dataSource.predicate` it should work.

https://github.com/SyncDB/DATASource/blob/master/Source/DATASource.swift#L120

**Comment by dneykov** [comment]
That will do it.
Thanks a lot.
