### ISSUE TITLE
Multiple cell identifier support

### ISSUE THREAD

**Issue by MojtabaHs** [SyncDB/DATASource#88]
Some times we want to entirely change the cell and load it from different xib or etc. at specific situations but this cool framework limits cell identifier to just one static reusable cell. I'm very interested to know is there a good reason behind this?

Thanks

**Comment by 3lvis** [comment]
Hi @MojtabaHs,

This was added 10 days ago. https://github.com/SyncDB/DATASource/pull/82

I'll take some time to add it to the README.

**Comment by MojtabaHs** [comment]
hmmmm. I see. Index path for cell with id is a good solution. But some times data source object should decide witch cell id should be used. The solution you mentioned is good but its need some index path storing and passing the array to delegate and etc. But it could easily achieved at initial time... if you know what I mean.

**Comment by 3lvis** [comment]
I'm sorry. I don't follow. Maybe you could more information about your use case. Like how your interface looks and how your data is stored, do you separate by sections? Etc.

I see an opportunity to add an awesome feature and would be nice if we could collaborate to make it happen :)

**Comment by MojtabaHs** [comment]
Imagine a conversation app like apple native messages. some messages contains only emoji, some only images, videos, maps and etc. Each one has its own xib (I think) and the table view datasource contain all of them. at cell initialization we could have something like:
 if (message.containsOnlyVideo) {
     cell = videoOnly cell from nib
}

I hope you get the idea. And about collaborate, I love to. But at this time, I'm working on some other part of my application and it will be my next job ;)

**Comment by 3lvis** [comment]
I think that should work with what added on https://github.com/SyncDB/DATASource/pull/82

**Comment by 3lvis** [comment]
I'll make sure to add a demo project to check that we're on the same page :)

**Comment by 3lvis** [comment]
Added an issue for this https://github.com/SyncDB/DATASource/issues/91
